name: "Fix styling with php-cs-fixer"

on:
  pull_request:
  push:

jobs:
  php-cs-fixer:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-versions: ['8.0']
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Fix Style"
        uses: "docker://oskarstark/php-cs-fixer-ga"
        with:
            args: "--config=.php-cs-fixer.dist.php --allow-risky=yes"

      - name: "Extract branch name"
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: "Commit changes"
        uses: "stefanzweifel/git-auto-commit-action@v2.3.0"
        with:
            commit_message: "Fix styling"
            branch: "${{ steps.extract_branch.outputs.branch }}"
        env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
